### ISSUE TITLE
Records protobuf definition is still 1.2

### ISSUE THREAD

**Issue by makapuf** [axiros/rusp#10]
As header of file `src/usp_record.rs` indicates : 
```
// Automatically generated rust module for 'usp-record-1-2.proto' file
```
whereas the .proto file  is 1.3

**Comment by therealprof** [comment]
Thanks for noticing, however 1.2 and 1.3 are identical so there's no point in regenerating the file just for the sake of fixing the comment.

**Comment by makapuf** [comment]
Thanks for your quick answer ! I think there is some difference, though : the record `UDSConnectRecord`has been added to `Record` (... and I would like to use it!)

**Comment by therealprof** [comment]
Hm, you're right. How would you like to use that?

**Comment by makapuf** [comment]
.. well, connecting to an agent using a unix domain socket (but I haven't achieved to making it work yet ;) )

**Comment by therealprof** [comment]
Yeah, but what do you want to use rusp for in that context? That Record type only exists for consistency, there's no additional information in it.

**Comment by xfmoulet** [comment]
If I need to use it (which I'm not sure but I need to connect to UDS, so ..), the record would need to be present and the ID would need to be 13, no ? But maybe it's not needed or useful *yet*. feel free to close it

**Comment by makapuf** [comment]
Hi, maybe it's not that useful now, but if I need it to connect to USP, the record id is 13 which can be useful ? not sure if the record is useful yet, so feel free to close.

**Comment by therealprof** [comment]
The use of the those Connect Record types is optional anyway. I'll update the code.
